settings:
  project_name: "aic-hcmc2020"  # also the folder name of the dataset that under datasets folder
  train_imgs: images
  val_imgs: images
  train_anns: annotations/instances_train.json
  val_anns: annotations/instances_val.json

  # mean and std in RGB order, actually this part should remain unchanged as long as your dataset is similar to coco.
  

  # this is coco anchors, change it if necessary
  anchors_scales: '[2 ** 0, 2 ** (1.0 / 3.0), 2 ** (2.0 / 3.0)]'
  anchors_ratios: '[(1.0, 1.0), (1.4, 0.7), (0.7, 1.4)]'

  # must match your dataset's category_id.
  # category_id is one_indexed,
  # for example, index of 'car' here is 1, while category_id of is 2
  obj_list: [
    'motorbike',
    'car',
    'bus',
    'truck'
  ]

  # custom augmentations
  
  mean: [0.5, 0.5, 0.5]
  std: [0.5, 0.5, 0.5]
  image_size: [512,512]
  keep_ratio: False