settings:
  #################   DATASET CONFIG   ###################

  project_name: "vinai1024-noratio"    # also the folder name of the dataset that under ./datasets folder
  train_imgs: images/train
  val_imgs: images/train
  test_imgs: images/test
  train_anns: annotations/1024_noratio_fold0_train.json
  val_anns: annotations/1024_noratio_fold0_val.json

  obj_list: [
    'No Finding',                       #Background
    'Aortic enlargement', 
    'Atelectasis', 
    'Calcification',
    'Cardiomegaly',
    'Consolidation',
    'ILD',
    'Infiltration',
    'Lung Opacity',
    'Nodule/Mass',
    'Other lesion',
    'Pleural effusion',
    'Pleural thickening',
    'Pneumothorax',
    'Pulmonary fibrosis'
  ]


  #################   TRAINING CONFIG   ###################
  
  batch_size: 4
  num_workers: 4
  
  image_size: [1024,1024]
  keep_ratio: False                     # whether to use resize padding

  cutmix: True
  mixup: True

  # gradient accumulation
  mixed_precision: False                # whether to use nvidia apex
  total_accumulate_steps: 64            # step * batch_size