settings:
  #################   DATASET CONFIG   ###################

  project_name: "vinai1024-noratio"    # also the folder name of the dataset that under ./datasets folder
  train_imgs: images/train
  val_imgs: images/train
  test_imgs: images/test
  train_anns: annotations/1024_noratio_fold0_train.json
  val_anns: annotations/1024_noratio_fold0_val.json

  obj_list: [
    'No Finding',                       #Background
    'Aortic enlargement', 
    'Atelectasis', 
    'Calcification',
    'Cardiomegaly',
    'Consolidation',
    'ILD',
    'Infiltration',
    'Lung Opacity',
    'Nodule/Mass',
    'Other lesion',
    'Pleural effusion',
    'Pleural thickening',
    'Pneumothorax',
    'Pulmonary fibrosis'
  ]


  #################   TRAINING CONFIG   ###################
  
  gpu_devices: '0,1'                     # supports multi-gpus
  num_epochs: 100
  batch_size: 4
  num_workers: 4

  min_iou_val:  0.5                     # IOU threshold for validation
  min_conf_val: 0.01                    # Confidence score threshold for validation
  max_images_val: 10000                 # max number of images for validation
  
  image_size: [1024,1024]               # [512, 640, 768, 896, 1024, 1280, 1280, 1536, 1536]
  keep_ratio: False                     # whether to use resize padding

  cutmix: True
  mixup: True

  # learning rate policy
  lr_policy:
    name: "adam"                         #[adam|sgd]
    lr: 0.01                            #[adam: 1e-3 | sgd: 1e-2]
    momentum: 0.937
    weight_decay: 0.0005


  # gradient accumulation
  mixed_precision: False                # whether to use nvidia apex
  total_accumulate_steps: 8            # step * batch_size, not use if equal 0

  # Test time augmentation
  tta: True                             # whether to use TTA while validation
  tta_ensemble_mode: "wbf"              # ensemble method when TTA